<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IM-RT-LP-621" failures="1" tests="8" name="testcases.MyOrdersTest" time="2.313" errors="0" timestamp="2023-06-27T23:20:41 IST" skipped="0">
  <testcase classname="testcases.MyOrdersTest" name="download" time="0.294"/>
  <system-out/>
  <testcase classname="testcases.MyOrdersTest" name="MyOrder" time="0.408"/>
  <system-out/>
  <testcase classname="testcases.MyOrdersTest" name="viewYourReturnRequest" time="0.517"/>
  <system-out/>
  <testcase classname="testcases.MyOrdersTest" name="recurringPayment" time="0.201"/>
  <system-out/>
  <testcase classname="testcases.MyOrdersTest" name="viewYourReturnReque" time="0.239">
    <failure message="expected [viewYourReturnRequest] but found [View your return requests]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [viewYourReturnRequest] but found [View your return requests]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at testcases.MyOrdersTest.viewYourReturnReque(MyOrdersTest.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- viewYourReturnReque -->
  <system-out/>
  <testcase classname="testcases.MyOrdersTest" name="yourRewardPoint" time="0.136"/>
  <system-out/>
  <testcase classname="testcases.MyOrdersTest" name="yourTransactions" time="0.154"/>
  <system-out/>
  <testcase classname="testcases.MyOrdersTest" name="viewyourorderhis" time="0.364"/>
  <system-out/>
</testsuite> <!-- testcases.MyOrdersTest -->
